name: Automerge

on:
  workflow_dispatch:
  schedule:
    # You can setup schedule here
    - cron: '1  * * *'

env:
  # replace "zinnsu" with your GitHub username 
  # replace "github.com/zinnsu/manpower.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://zinnsu:${{secrets.GITHUB_TOKEN}}@github.com/zinnsu/manpower.git
  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: develop

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/zinnsu/manpower.git

  # replace "master" with your master branch name
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with main
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "zinnsu"
        git config user.email "zinnsu.solution@gmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
